<a href="https://colab.research.google.com/github/wafiabbas/Apple-Sales-PowerBI-Dashboard/blob/main/emocommerce_sale.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [6]:
df=pd.read_excel("Ecommerce_Unclean_Project.xlsx")

In [7]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [8]:
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    object
 1   Order_Date     524 non-null    object
 2   Customer_Name  524 non-null    object
 3   Email          524 non-null    object
 4   Phone          502 non-null    float64
 5   City           524 non-null    object
 6   State          524 non-null    object
 7   Product        524 non-null    object
 8   Category       524 non-null    object
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    object
 13  Order_Status   524 non-null    object
 14  Delivery_Date  503 non-null    object
dtypes: float64(3), object(12)
memory usage: 61.5+ KB

In [10]:
df.shape

(524, 15)